apiVersion: apps/v1
kind: Deployment
metadata:
  name: tapp
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tapp
  template:
    metadata:
      labels:
        app: tapp
    spec:
      containers:
      - name: tapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
