apiVersion: apps/v1
kind: Deployment
metadata:
  name: tapp
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tapp
  template:
    metadata:
      labels:
        app: tapp
    spec:
      containers:
      - name: tapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80


---------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  namespace: appdemo
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
        - name: myapp1
          image: nginx:latest
          ports:
            - containerPort: 80