apiVersion: v1
kind: Pod
metadata:
  name: tapp
  namespace: myapp
spec:
  containers:
  - name: tapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080

