apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  namespace: appdemo
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
        - name: myapp1
          image: nginx:latest
          ports:
            - containerPort: 80